export const QUOTES = [
  "Quality is not an act, it is a habit.",
  "Small daily improvements are the key to staggering long-term results.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Don't watch the clock; do what it does. Keep going.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Your future is created by what you do today, not tomorrow.",
  "The best way to predict the future is to create it.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Dream big and dare to fail.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The secret of getting ahead is getting started.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Don't count the days, make the days count.",
  "The mind is everything. What you think you become.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Winning isn't everything, but wanting to win is.",
  "Whether you think you can or you think you can't, you're right.",
  "The best revenge is massive success.",
  "A person who never made a mistake never tried anything new.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Creativity is intelligence having fun.",
  "Everything has beauty, but not everyone sees it.",
  "Do what you can, with what you have, where you are.",
  "Happiness depends upon ourselves.",
  "Turn your wounds into wisdom.",
  "The journey of a thousand miles begins with one step.",
  "If you want to lift yourself up, lift up someone else.",
  "Be the change that you wish to see in the world.",
  "Innovation distinguishes between a leader and a follower.",
  "The power of imagination makes us infinite.",
  "Action is the foundational key to all success.",
  "I never dreamed about success, I worked for it.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The way to get started is to quit talking and begin doing.",
  "Focus on being productive instead of busy.",
  "If you're going through hell, keep going.",
  "The only person you are destined to become is the person you decide to be.",
  "Don't be afraid to give up the good to go for the great.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Limitations live only in our minds.",
  "The standard you walk past is the standard you accept.",
  "Great things never come from comfort zones.",
  "Do one thing every day that scares you.",
  "Failure is the condiment that gives success its flavor.",
  "Strive not to be a success, but rather to be of value.",
  "Opportunities don't happen. You create them.",
  "A goal is a dream with a deadline.",
  "Try to be a rainbow in someone else's cloud.",
  "Persistence guarantees that results are inevitable.",
  "Make each day your masterpiece.",
  "Discipline is the bridge between goals and accomplishment.",
  "If you tell the truth, you don't have to remember anything.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Character is doing the right thing when nobody is looking.",
  "Your passion is waiting for your courage to catch up.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Courage is grace under pressure.",
  "If you can dream it, you can do it.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Knowledge is power.",
  "The more that you read, the more things you will know.",
  "In the middle of every difficulty lies opportunity.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Genius is 1% inspiration and 99% perspiration.",
  "Integrity is the essence of everything successful.",
  "Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "Light tomorrow with today.",
  "Act as if what you do makes a difference. It does.",
  "The sun himself is weak when he first rises, and gathers strength as the day gets on.",
  "Never leave that till tomorrow which you can do today.",
  "Well done is better than well said.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "He who has a why to live can bear almost any how.",
  "You must do the things you think you cannot do.",
  "Success usually comes to those who are too busy to be looking for it.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Take up one idea. Make that one idea your life.",
  "All our dreams can come true if we have the courage to pursue them.",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "A year from now you may wish you had started today.",
  "The successful warrior is the average man, with laser-like focus.",
  "Don't let the noise of others' opinions drown out your own inner voice.",
  "Don't be embarrassed by your failures, learn from them and start again.",
  "If you look at what you have in life, you'll always have more.",
  "The only way to find the limits of the possible is by going beyond them into the impossible.",
  "Everything you can imagine is real.",
  "Simplicity is the ultimate sophistication.",
  "Tough times never last, but tough people do.",
  "Problems are not stop signs, they are guidelines.",
  "Believe in yourself! Have faith in your abilities!",
  "Work hard in silence, let your success be your noise.",
  "The bigger the challenge, the greater the glory.",
  "You miss 100% of the shots you don't take.",
  "Change your thoughts and you change your world.",
  "Life is short, and it is up to you to make it sweet.",
  "Small acts, when multiplied by millions of people, can transform the world.",
  "Start where you are. Use what you have. Do what you can.",
  "Every moment is a fresh beginning.",
  "To be the best, you must be able to handle the worst."
];


